project = 'Hướng dẫn calibration camera bằng Kalibr và Docker'
author = 'Edge Computer'
language = 'vi'
extensions = []
root_doc = 'index'
html_theme = 'sphinx_rtd_theme'
html_title = 'Kalibr'
html_show_sourcelink = False
html_show_sphinx = False
html_show_copyright = False
html_static_path = ['_static']
html_css_files = ['custom.css']
exclude_patterns = []
