FROM osrf/ros:noetic-desktop-full

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
    git wget autoconf automake nano \
    python3-dev python3-pip python3-scipy python3-matplotlib \
    ipython3 python3-wxgtk4.0 python3-tk python3-igraph python3-pyx \
    libeigen3-dev libboost-all-dev libsuitesparse-dev \
    doxygen \
    libopencv-dev \
    libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
    python3-catkin-tools python3-osrf-pycommon \
    byobu \
    && rm -rf /var/lib/apt/lists/*

ENV WORKSPACE=/catkin_ws
ENV MPLBACKEND=Agg
ENV KALIBR_MANUAL_FOCAL_LENGTH_INIT=1

RUN mkdir -p $WORKSPACE/src && \
    cd $WORKSPACE && \
    catkin init && \
    catkin config --extend /opt/ros/noetic && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

COPY ./src/kalibr $WORKSPACE/src/kalibr

RUN cd $WORKSPACE && catkin build -j$(nproc)

RUN echo '#!/bin/bash\n\
set -e\n\
source "$WORKSPACE/devel/setup.bash"\n\
export MPLBACKEND=Agg\n\
export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1\n\
exec "$@"' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
